# Generated by Django 2.2.6 on 2019-11-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photosend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='photo',
        ),
    ]
