# Generated by Django 2.2.6 on 2019-11-04 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photosend', '0002_auto_20191104_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photosend.Photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='like_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
